services:
  postgres:
    image: postgres:16-alpine
    container_name: mockify-postgres
    environment:
      POSTGRES_DB: mockify
      POSTGRES_USER: mockify_user
      POSTGRES_PASSWORD: mockify_password
    ports:
      - "5432:5432"
    volumes:
      - mockify_data:/var/lib/postgresql/data

volumes:
  mockify_data:
